### PR TITLE
Keep the application on the player page when a new video is opened while another on is playing

### PR DESCRIPTION
**Pull request by volfpeter**
See #219 for issue description

Notes:
There might be a better solution to this problem (adding an extra signal when a video starts playing and navigating the application to the player page when it is emitted), but I didn't want (and had the time) to refactor the application, so I implemented a much simpler solution. It prevents `Playlist.clear_items()` from emitting `stop_video()` (taking the application back to the welcome page) in the specific case that is described in the issue - all other use-cases remain unchanged. I hope this is acceptable.

### CODE REVIEW

**Review by jeremypw — APPROVED** [review]
As you say, there is probably a more elegant solution with refactoring but this does the job and is not likely to cause regressions.  Thanks.

**Comment by volfpeter** [comment]
Thanks for the quick review!

**Comment by volfpeter** [comment]
@jeremypw Could you please merge this PR?

**Comment by jeremypw** [comment]
As no one has raised any objections I will now merge.

**Comment by volfpeter** [comment]
@jeremypw Thanks again!

**Pull request merged**
