### PR TITLE
Navigation button bug

### PR DESCRIPTION
**Pull request by markodp**
If you are opening videos with file manager while already playing another one, navigation button changes from "Back" to "Library" and eventually "Episodes".

### CODE REVIEW

**Comment by Philip-Scott** [comment]
Opening another video while playing honestly feels like a bug since it's now just cycling between all of the states. 

IMO, opening a file from the File Manager should make the back button either:

- point to the Episodes list (If it's in an "series" folder)
- if not, choose BACK so that clicking it always shows the Welcome screen from a file opened through the File manager

But this is a @elementary/ux desision :)

**Comment by markodp** [comment]
Done. Now if file opened form file manager is in library, navigation button changes to Library or Episodes - same as if it was opened from app library.

For files outside of library, Back button is always shown. I am not sure if you wanted me to detect episodes outside of library, but i don't think detection would be accurate enough, at least not with current way of detecting episodes. If i would open video from ~/Downloads, it would detect folder as series if i had several unrelated video files in it... if i understood the code correctly :)

I also fixed/updated navigation button when file from playlist is selected or when it auto-plays next file.

**Comment by cassidyjames** [comment]
Looks like @elementary/ux agrees with @Philip-Scott :stuck_out_tongue:

**Comment by jeremypw** [comment]
This does not run on Juno as it expects org.pantheon.audience to be present (it has migrated to io.elementary.videos).  Not sure why Github is not showing the difference or indicating that this PR is behind master in this respect (for me).

**Comment by markodp** [comment]
I've merged it locally, hope it works now.

**Comment by jeremypw** [comment]
Now runs, thanks.  I havent had a chance to test extensively but it seems to work.  I am not that familiar with the codebase but I am concerned that there is at least two ways the PlayerPage can call its "play_file" method - either directly or by emitting a "play_requested" signal to Window.  It could also obtain the Window object and call its public play_file directly.  Is there a good reason for this multiplicity of pathways?  Can it be simplified?

**Comment by jeremypw** [comment]
Probably best to put all the corrective stuff in a different PR.  Is the new poster_initialized stuff essential for this fix?

**Comment by markodp** [comment]
Ah, you are right, it can be simplified that way. Thanks, pushed the fix.

If i can remember correctly, if i opened episode video from file manager that was in the library and then navigated back, posters were not shown. I don't think it was issue introduced with my code, but it does relate to navigation.

**Comment by jeremypw** [comment]
This better.  The fix seems to work OK.  The diff seems messy but that is because 
1) It is addresses three different issues (navigation button label, posters and variable names)  which I think could have been 3 separate PRs.
2) The existing code is messy and needs refactoring to to simplify and DRY it.

I am inclined to approve this for merging and hope the existing code gets sorted at some point.

**Pull request merged**
