### PR TITLE
MediaControls: minimal transparent style

### PR DESCRIPTION
**Pull request by danirabbit**
Screenshot from 2024-05-22 09 17 43

Much more minimal appearance but using lots of shadows and things to give contrast

### CODE REVIEW

**Comment by danirabbit** [comment]
Ah i probably need to bump granite requirement in meson maybe

**Comment by danirabbit** [comment]
@leolost2605 okay bumped granite requirement. This branch is using a feature of the latest granite release

**Review by leolost2605 — CHANGES_REQUESTED** [review]
Looks amazing ~but I get this warning multiple times when opening a popover e.g. the playlistpopover~
~`
(io.elementary.videos:2): Gtk-CRITICAL **: 19:38:07.661: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
`~

Very minor nitpick but is it possible to keep close/maximize buttons at the same position as they are on the other pages? Would make the transition IMHO a bit smoother :)

Also is there a trick/way to build this without changing the runtime version to daily? Or how does CI handle it? 😅

**Review by leolost2605 — DISMISSED** [review]

**Comment by leolost2605** [comment]
Nvm that seems to have been cause by the daily runtime/sdk

**Comment by danirabbit** [comment]
Gonna merge because I've got a lot of thumbs up here from contributors

**Pull request merged**
