### PR TITLE
Restore Library View functionality

### LINKED ISSUE #205: Library View never appears due to non-set setting
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Library View in-app never appears, because in-code its related setting is never set to the User's Videos folder, so the app only shows the Welcome View and the Player View.

### To Reproduce
Open Videos with lots of videos in the Videos folder. Instead of a Library View option, there's only an option to open a single video.

### Expected behavior
It should set the `library-view` setting to point to the User's Videos folder and thus restore functionality to the app.

### Screenshots or screen recordings
N/A

### Logs
N/A

## Platform Information
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
N/A

### PR DESCRIPTION
**Pull request by lainsce**
This restores all the Library View functions inside Videos that seemingly never could be reached.

|Welcome Screen|Library View|
|:---:|:---:|
|Screenshot from 2020-07-21 01 18 45|Screenshot from 2020-07-21 01 19 54|

Fixes #205

### CODE REVIEW

**Comment by lainsce** [comment]
I got it constantly, this helps fix it. These values on the `if` are from the gschema defaults, so no room for error here since as soon as it opens, these are updated and so the if-check isn't needed.

**Comment by jeremypw** [comment]
I think the real problem is in these lines:
```
                File library_folder = File.new_for_path (settings.get_string ("library-folder"));
                if (library_folder.get_path () == "" || !library_folder.query_exists ()) {
```
if the "library-folder" setting is "" then the library_folder path is *not* ""!  When launched from the terminal it is the current working directory (which may not have any videos in so the Browse Library button is not visible).  When launched from dock it is the user home directory which may or may not have videos in.  The correct solution is to test the setting directly.
```
                if (settings.get_string ("last-folder") == "-1") {
                    settings.set_string ("last-folder", GLib.Environment.get_user_special_dir (GLib.UserDirectory.VIDEOS));
                }

                var library_path = settings.get_string ("library-folder");
                File library_folder = File.new_for_path (library_path);
                if (library_path ="" || !library_folder.query_exists ()) {
                    settings.set_string ("library-folder", GLib.Environment.get_user_special_dir (GLib.UserDirectory.VIDEOS));
                };
```

**Comment by jeremypw** [comment]
Ideally there needs to be UX for setting the library folder anyway.  What are your views on https://github.com/elementary/videos/issues/194?

**Comment by lainsce** [comment]
IMO, these things of setting libraries should indeed be a setting on the Applications plug, but for now, fixing the faulty code will help users in small-term. I'll use your suggested code.

**Pull request merged**
