### PR TITLE
Respect dark style preference

### PR DESCRIPTION
**Pull request by leolost2605**
Currently we always force dark mode. This will allow the user to toggle it off in a new app menu.

### CODE REVIEW

**Comment by danirabbit** [comment]
Do we need to add a setting for this? Should we just follow the system style like other apps?

**Comment by leolost2605** [comment]
I personally don't need a setting. But I can imagine some would prefer to have Videos always dark which is why it's currently the default 🤷

**Comment by danirabbit** [comment]
@leolost2605 I think we should try just following the system setting first and see if we get feedback about it! New cycle is the perfect time to try new things :)

**Comment by leolost2605** [comment]
@danirabbit done :)

**Review by danirabbit — APPROVED** [review]
🚀

**Pull request merged**
