### PR TITLE
Flatpak: Allow Write Access to Library and Thumbnails Cache Folders

### LINKED ISSUE #282: Videos fails to move to trash
### What Happened?

Now Odin comes with the flatpaked version of Videos, and since [it has only read permission](https://github.com/elementary/videos/blob/a0c2b7d5d0122aae628a6f03196e650a5990bcaa/io.elementary.videos.yml#L8) it can't move videos to trash in the library.

### Steps to Reproduce

1. Prepare some videos in your library
2. Open Videos and browse your library
3. Secondary-click some video listed and select "Move to Trash"
4. Nothing happens
5. Click the video you just tried to trash; Videos crashes

### Expected Behavior

Videos should have write access to the library; or remove "Move to Trash" function if we want to keep Videos read-only against files

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
** (io.elementary.videos:2): WARNING **: 16:23:18.210: LibraryItem.vala:221: Failed to open /home/ryonakano/Videos/test-file.mp4
**
ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)
Bail out! ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)
```

### Hardware Info

N/A

### PR DESCRIPTION
**Pull request by Marukesu**
we need to have write access to move files to trash.

fixes #282.

### CODE REVIEW

**Review by jeremypw — COMMENTED** [review]
I can confirm that this allows trashing videos from the library view (which fails in master).

However, pressing the "Restore" button in the toast notification gives a terminal message "LibraryManager.vala:221: Operation not supported".  Can this be fixed as well or does it need a separate PR?

**Comment by Marukesu** [comment]
> However, pressing the "Restore" button in the toast notification gives a terminal message "LibraryManager.vala:221: Operation not supported". Can this be fixed as well or does it need a separate PR?

The problem is that the [Trash portal](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Trash) doesn't have an RestoreFile method, so we need to change the code to stop trashing when the user ask and only do it when the application is closed.

I can do that here if it seems better than in another PR.

**Comment by jeremypw** [comment]
If you could just remove the non-functional "Restore" button (when using the portal) I am not sure we need to delay doing the trashing.  I guess we have to assume users know how to get stuff back from trash using Files or the dock widget.  Presumably this limitation will affect any Flatpak application that uses the Trash portal.

**Comment by jeremypw** [comment]
Or were you intending to "fake" the trashing so that it could be reverted while the app was open?

**Comment by Marukesu** [comment]
>

**Comment by jeremypw** [comment]
The only problem with fake trashing is that if the app does not close cleanly (e.g. the user just logs out) then the files will reappear next time it is run.

**Comment by Marukesu** [comment]
Updated the PR, now when using the flatpak version the toast don't show an "Restore" option and `<Ctrl>+Z` do nothing.

**Review by jeremypw — APPROVED** [review]
This works well for single videos now - thanks!

Only possible issue I saw was that trashing failed when applied to a folder even though the option was still offered in the context menu (and a folder item appears the same as a single video in the library view).

I think this can be addressed in a separate PR - may need to look the UI for folders.

**Pull request merged**
